# Kitty Configuration

shell_integration disabled
confirm_os_window_close 2

####################################
### Set the font family and size ###
####################################

font_family FiraCode Nerd Font Mono
font_size 16.0

################################
### Background customization ###
################################

background_opacity .75
background_blur 30
# transparent_background_colors #333333@0.7
# dynamic_background_opacity yes

##################################
### Include external them file ###
##################################

include themes/macchiato.conf

#############################
### Window Layout Styling ###
#############################

window_padding_width 5
window_margin_width 2
inactive_text_alpha 0.5
window_border_width 3pt
hide_window_decorations titlebar-only
active_border_color #89DCEB
inactive_border_color #313244

############################
### Cursor customization ###
############################

cursor_shape beam
cursor_blink_interval 0.5
cursor_beam_thickness 3
cursor_shape_unfocused underline
cursor_trail 1

###########################
### Scrollback settings ###
###########################

scrollback_lines 5000

##########################
### Tab bar appearance ###
##########################

tab_bar_edge bottom
tab_bar_margin_width 0.0
tab_bar_margin_height 2.0 0.0
tab_bar_style powerline
tab_bar_align left
tab_bar_min_tabs 2
tab_powerline_style slanted
tab_activity_symbol 
tab_title_template "{index}: {title}"
active_tab_title_template "{index}: {title}"
tab_switch_strategy previous

#################
### Title Bar ###
#################

macos_show_window_title_in menubar

#####################
### Miscellaneous ###
#####################

placement_strategy center

#########################
### Window Management ###
#########################

map ctrl+shift+enter new_window_with_cwd
map ctrl+shift+] next_window
map ctrl+shift+[ previous_window
map ctrl+shift+w close_window

#########################
### Layout management ###
#########################

map ctrl+shift+l next_layout

##################
### Tab actions ###
##################

map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+right next_tab
map ctrl+shift+left previous_tab
map ctrl+shift+. move_tab_forward
map ctrl+shift+, move_tab_backward
map ctrl+shift+alt+t set_tab_title
map ctrl+shift+q close_tab
map ctrl+shift+p select_tab
map ctrl+shift+1 goto_tab 1
map ctrl+shift+2 goto_tab 2
map ctrl+shift+3 goto_tab 3
map ctrl+shift+4 goto_tab 4
map ctrl+shift+5 goto_tab 5
map ctrl+shift+6 goto_tab 6
map ctrl+shift+7 goto_tab 7
map ctrl+shift+8 goto_tab 8
map ctrl+shift+9 goto_tab 9
